---
kind: pipeline
type: docker
name: Production pipeline

steps:
  - name: publish image to production
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_production
      secret_key:
        from_secret: aws_access_key_secret_production
      region: eu-west-1
      repo:   cust-production-newsletter-ecr/nyhedsbreveprofil
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - latest
        - ${CI_COMMIT_SHA}

  - name: Deploy to production
    image: pelotech/drone-ecs:1.0.7
    environment:
      NYHEDSBREVEPROFIL_APP_ID:
        from_secret: nyhedsbreveprofil_app_id_prod
      NYHEDSBREVEPROFIL_APP_SECRET:
        from_secret: nyhedsbreveprofil_app_secret_prod
      ZENDESK_API_EMAIL:
        from_secret: zendesk_api_email_prod
      ZENDESK_API_TOKEN:
        from_secret: zendesk_api_token_prod
      GIGYA_API_KEY:
        from_secret: gigya_api_key_prod
      GIGYA_API_USER:
        from_secret: gigya_api_user_prod
      GIGYA_API_SECRET:
        from_secret: gigya_api_secret_prod
      GA_TRACKING_ID:
        from_secret: ga_tracking_id_prod
      ARIA_CLIENT_NO:
        from_secret: aria_client_no_prod
      ARIA_AUTH_KEY:
        from_secret: aria_auth_key_prod
    settings:
      secret_environment_variables:
        - NYHEDSBREVEPROFIL_APP_ID
        - NYHEDSBREVEPROFIL_APP_SECRET
        - ZENDESK_API_EMAIL
        - ZENDESK_API_TOKEN
        - GIGYA_API_KEY
        - GIGYA_API_USER=AADC9FWioQwh
        - GIGYA_API_SECRET
        - GA_TRACKING_ID
        - ARIA_CLIENT_NO
        - ARIA_AUTH_KEY
      environment_variables:
        - MDBAPI_ADDRESS=http://10.94.93.46:8000 #set prod value
        - BPC_URL=https://bpc.berlingskemedia-testing.net #set prod value
        - ZENDESK_URL=https://berlingskemediahelp.zendesk.com #set prod value
        - ARIA_HOST=https://eu-stage03.workflow.ariasystems.net/bpa/c_DePersgroepQA01 #set prod value
      aws_access_key_id:
        from_secret: aws_access_key_production
      aws_secret_access_key:
        from_secret: aws_access_key_secret_production
      cluster: cust-production-newsletter
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-production-newsletter-ecr/nyhedsbreveprofil
      container_name: cust-production-newsletter-nyhedsbreveprofil-container
      family: cust-production-newsletter-nyhedsbreveprofil
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-production-newsletter
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=cust-production-newsletter-nyhedsbreveprofil
      memory: 512
      port_mappings:
        - 8000 8000
      region: eu-west-1
      service: cust-production-newsletter-nyhedsbreveprofil
      service_network_security_groups:
      [security_groups]
      service_network_subnets:
      [subnets]
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-production-newsletter-nyhedsbreveprofil-exec
      task_memory: 512
      task_network_mode: awsvpc

trigger:
  repo:
    - BerlingskeMedia/nyhedsbreveprofil
  branch:
    - master
  event:
    include:
      - push
    exclude:
      - pull_request

---
kind: pipeline
type: docker
name: test pipeline

steps:
  - name: publish image to test
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      region: eu-west-1
      repo: cust-test-newsletter-ecr/nyhedsbreveprofil
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - ${DRONE_TAG}-${CI_COMMIT_SHA}
        - ${CI_COMMIT_SHA}

  - name: Deploy to test QA1
    image: pelotech/drone-ecs:1.0.7
    environment:
      NYHEDSBREVEPROFIL_APP_ID:
        from_secret: nyhedsbreveprofil_app_id_test
      NYHEDSBREVEPROFIL_APP_SECRET:
        from_secret: nyhedsbreveprofil_app_secret_test
      ZENDESK_API_EMAIL:
        from_secret: zendesk_api_email_test
      ZENDESK_API_TOKEN:
        from_secret: zendesk_api_token_test
      GIGYA_API_KEY:
        from_secret: gigya_api_key_test
      GIGYA_API_USER:
        from_secret: gigya_api_user_test
      GIGYA_API_SECRET:
        from_secret: gigya_api_secret_test
      GA_TRACKING_ID:
        from_secret: ga_tracking_id_test
      ARIA_CLIENT_NO:
        from_secret: aria_client_no_test
      ARIA_AUTH_KEY:
        from_secret: aria_auth_key_test
    settings:
      secret_environment_variables:
        - NYHEDSBREVEPROFIL_APP_ID
        - NYHEDSBREVEPROFIL_APP_SECRET
        - ZENDESK_API_EMAIL
        - ZENDESK_API_TOKEN
        - GIGYA_API_KEY
        - GIGYA_API_USER=AADC9FWioQwh
        - GIGYA_API_SECRET
        - GA_TRACKING_ID
        - ARIA_CLIENT_NO
        - ARIA_AUTH_KEY
      environment_variables:
        - MDBAPI_ADDRESS=http://10.94.93.46:8000 #set prod value
        - BPC_URL=https://bpc.berlingskemedia-testing.net #set prod value
        - ZENDESK_URL=https://berlingskemediahelp.zendesk.com #set prod value
        - ARIA_HOST=https://eu-stage03.workflow.ariasystems.net/bpa/c_DePersgroepQA01 #set prod value
      cluster: cust-test-newsletter
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-test-newsletter-ecr/nyhedsbreveprofil
      container_name: cust-test-newsletter-nyhedsbreveprofil-container
      family: cust-test-newsletter-nyhedsbreveprofil
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-test-newsletter
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=cust-test-newsletter-nyhedsbreveprofil
      memory: 512
      port_mappings:
        - 8000 8000
      region: eu-west-1
      service: cust-test-newsletter-nyhedsbreveprofil
      service_network_security_groups:
      [security_groups]
      service_network_subnets:
      [subnets]
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-test-newsletter-nyhedsbreveprofil-exec
      task_memory: 512
      task_network_mode: awsvpc
    when:
      ref:
        include:
          - refs/tags/qa1*
        exclude:
          - refs/heads/master

trigger:
  repo:
    - BerlingskeMedia/nyhedsbreveprofil
  event:
    - tag
  ref:
    include:
      - refs/tags/qa*
---
kind: "secret"
name: "aws_access_key_testing"
get:
  path: "[SSM_path]"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_testing"
get:
  path: "drone/userhandling-testing-pm"
  name: "aws_access_key_secret"
---
kind: "secret"
name: "aws_access_key_production"
get:
  path: "[SSM_path]"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_production"
get:
  path: "[SSM_path]"
  name: "aws_access_key_secret"
---
kind: "secret"
name: "my_test_ssm_secret"
get:
  path: "[SSM_path]"
  name: "some_ssm_value_name"
---
kind: "secret"
name: "my_production_ssm_secret"
get:
  path: "[SSM_path]"
  name: "some_ssm_value_name"
