---
kind: pipeline
type: docker
name: test pipeline

steps:
  - name: publish image to test
    image: plugins/ecr
    settings:
      onfig:
        from_secret: dockerhub_auth_config
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      region: eu-west-1
      repo: cust-testing-newsletter-ecr/nyhedsbreveprofil
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - ${DRONE_TAG}-${CI_COMMIT_SHA}
        - ${CI_COMMIT_SHA}

  - name: Deploy to test QA1
    image: pelotech/drone-ecs:1.0.7
    environment:
      NYHEDSBREVEPROFIL_APP_ID:
        from_secret: nyhedsbreveprofil_app_id_test_qa1
      NYHEDSBREVEPROFIL_APP_SECRET:
        from_secret: nyhedsbreveprofil_app_secret_test_qa1
      ZENDESK_API_EMAIL:
        from_secret: zendesk_api_email_test_qa1
      ZENDESK_API_TOKEN:
        from_secret: zendesk_api_token_test_qa1
      GIGYA_API_KEY:
        from_secret: gigya_api_key_test_qa1
      GIGYA_API_USER:
        from_secret: gigya_api_user_test_qa1
      GIGYA_API_SECRET:
        from_secret: gigya_api_secret_test_qa1
      GA_TRACKING_ID:
        from_secret: ga_tracking_id_test_qa1
      ARIA_CLIENT_NO:
        from_secret: aria_client_no_test_qa1
      ARIA_AUTH_KEY:
        from_secret: aria_auth_key_test_qa1
      MDBAPI_ADDRESS:
        from_secret: mdbapi_qa1_service_discovery
    settings:
      task_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-np-qa1-exec
      secret_environment_variables:
        - NYHEDSBREVEPROFIL_APP_ID
        - NYHEDSBREVEPROFIL_APP_SECRET
        - ZENDESK_API_EMAIL
        - ZENDESK_API_TOKEN
        - GIGYA_API_KEY
        - GIGYA_API_USER=AADC9FWioQwh
        - GIGYA_API_SECRET
        - GA_TRACKING_ID
        - ARIA_CLIENT_NO
        - ARIA_AUTH_KEY
        - MDBAPI_ADDRESS
      environment_variables:
        - BPC_URL=https://bpc.berlingskemedia-testing.net
        - ZENDESK_URL=https://berlingskemediahelp.zendesk.com
        - ARIA_HOST=https://eu-stage03.workflow.ariasystems.net/bpa/c_DePersgroepQA01
      cluster: cust-testing-newsletter
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-testing-newsletter-ecr/nyhedsbreveprofil
      container_name: cust-testing-newsletter-np-qa1-container
      family: cust-testing-newsletter-np-qa1
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-testing-newsletter
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=newsletter-np-qa1
      memory: 512
      port_mappings:
        - 8080 8080
      region: eu-west-1
      service: cust-testing-newsletter-np-qa1
      service_network_security_groups:
        - sg-04532122919e3abd0
        - sg-02796308224a5820e
      service_network_subnets:
        - subnet-061a8876f7f68ea21
        - subnet-0ace4f6a68677187c
        - subnet-01633ca14c693e302
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-np-qa1-exec
      task_memory: 512
      task_network_mode: awsvpc
    when:
      ref:
        include:
          - refs/tags/qa1*
        exclude:
          - refs/heads/master

#  - name: Deploy to test QA2
#    image: pelotech/drone-ecs:1.0.7
#    environment:
#      NYHEDSBREVEPROFIL_APP_ID:
#        from_secret: nyhedsbreveprofil_app_id_test_qa2
#      NYHEDSBREVEPROFIL_APP_SECRET:
#        from_secret: nyhedsbreveprofil_app_secret_test_qa2
#      ZENDESK_API_EMAIL:
#        from_secret: zendesk_api_email_test_qa2
#      ZENDESK_API_TOKEN:
#        from_secret: zendesk_api_token_test_qa2
#      GIGYA_API_KEY:
#        from_secret: gigya_api_key_test_qa2
#      GIGYA_API_USER:
#        from_secret: gigya_api_user_test_qa2
#      GIGYA_API_SECRET:
#        from_secret: gigya_api_secret_test_qa2
#      GA_TRACKING_ID:
#        from_secret: ga_tracking_id_test_qa2
#      ARIA_CLIENT_NO:
#        from_secret: aria_client_no_test_qa2
#      ARIA_AUTH_KEY:
#        from_secret: aria_auth_key_test_qa2
#    settings:
#      secret_environment_variables:
#        - NYHEDSBREVEPROFIL_APP_ID
#        - NYHEDSBREVEPROFIL_APP_SECRET
#        - ZENDESK_API_EMAIL
#        - ZENDESK_API_TOKEN
#        - GIGYA_API_KEY
#        - GIGYA_API_USER=AADC9FWioQwh
#        - GIGYA_API_SECRET
#        - GA_TRACKING_ID
#        - ARIA_CLIENT_NO
#        - ARIA_AUTH_KEY
#      environment_variables:
#        - MDBAPI_ADDRESS=http://10.94.93.46:8000
#        - BPC_URL=https://bpc.berlingskemedia-testing.net
#        - ZENDESK_URL=https://berlingskemediahelp.zendesk.com
#        - ARIA_HOST=https://eu-stage03.workflow.ariasystems.net/bpa/c_DePersgroepQA01
#      cluster: cust-testing-newsletter
#      compatibilities: FARGATE
#      deployment_configuration: 100 200
#      desired_count: 1
#      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-testing-newsletter-ecr/nyhedsbreveprofil
#      container_name: cust-testing-newsletter-np-qa2-container
#      family: cust-testing-newsletter-np-qa2
#      log_driver: awslogs
#      log_options:
#        - awslogs-group=cust-testing-newsletter
#        - awslogs-region=eu-west-1
#        - awslogs-stream-prefix=newsletter-np-qa2
#      memory: 512
#      port_mappings:
#        - 8080 8080
#      region: eu-west-1
#      service: cust-testing-newsletter-np-qa2
#      service_network_security_groups:
#        - sg-04532122919e3abd0
#        - sg-09120208d89ca170b
#      service_network_subnets:
#        - subnet-061a8876f7f68ea21
#        - subnet-0ace4f6a68677187c
#        - subnet-01633ca14c693e302
#      tag: ${CI_COMMIT_SHA}
#      task_cpu: 256
#      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-np-qa2-exec
#      task_memory: 512
#      task_network_mode: awsvpc
#    when:
#      ref:
#        include:
#          - refs/tags/qa2*
#        exclude:
#          - refs/heads/master

trigger:
  repo:
    - BerlingskeMedia/nyhedsbreveprofil
  event:
    - tag
  ref:
    include:
      - refs/tags/qa*
---
kind: secret
name: dockerhub_auth_config
get:
  path: drone/dockerhub_auth_secret
  name: auth_json
---
kind: "secret"
name: "aws_access_key_testing"
get:
  path: "drone/cust-production-newsletter"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_testing"
get:
  path: "drone/cust-testing-pm"
  name: "aws_access_key_secret"
---
kind: "secret"
name: "aws_access_key_production"
get:
  path: "drone/cust-production-newsletter"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_production"
get:
  path: "drone/cust-production-newsletter"
  name: "aws_access_key_secret"
